config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  get 'home/about' => 'homes#about', as: 'about'
  resources :homes, only: [:about]
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   has_many :post_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   
   def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
   end
   validates :title, presence: true
   validates :body, {presence: true, length: {maximum: 200}}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length:{maximum: 50}
  attachment :profile_image
  
  # 都道府県コードから都道府県名に自動で変換する。
  include JpPrefecture
  jp_prefecture :prefecture_code
  # ~.prefecture_nameで都道府県名を参照出来る様にする。
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [
    :user_name, 
    :email,:postcode,
    :prefecture_name,
    :address_city,
    :address_street, 
    :password, 
    :password_confirmation, 
    :remember_me
    ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     flash[:notice] =  "You have created book successfully."
     redirect_to book_path(@book)
   else
     @user = current_user
     @books = Book.all
     render :index
   end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def show
    @book = Book.find(params[:id])
    @post_comment = PostComment.new
    @user = @book.user
    @books = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

# private---------------------------------------
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    if current_user != @user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!
    def create
        @book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: @book.id)
        favorite.save
        # redirect_back fallback_location: root_path
    end

    def destroy
        @book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: @book.id)
        favorite.destroy
        # redirect_back fallback_location: root_path

    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
    def create
        @book = Book.find(params[:book_id])
        comment = current_user.post_comments.new(post_comment_params)
        comment.book_id = @book.id
        comment.user_id = current_user.id

        comment.save
        # redirect_to book_path(book)
    end
    def destroy
        @book = Book.find(params[:book_id])
        post_comment = @book.post_comments.find(params[:id])
		post_comment.destroy

        # redirect_to book_path(params[:book_id])
    end

    private

      def post_comment_params
        params.require(:post_comment).permit(:comment)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to  user_path(@user)
    else
      render :edit
    end
  end

# private------------------------------------------------------
  private
  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
       redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newBook.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book, local:true do |f| %>
    <div class="form-group">
        <label>Title</label>
        <%= f.text_field :title , class: "form-control book_title" %>
    </div>
    <div class="form-group">
        <label>Body</label>
        <%= f.text_area :body , class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book" , class: "btn btn-success"%>
    </div>
<% end  %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <%= render 'layouts/errors', error: @book %>
      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, autofocus: true, class:"form-control book_title",id:"book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_field :body, autofocus: true,class:"form-control book_opinion" ,id:"book_opinion"  %>
        </div>
        <div class="form-group">
           <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path %> | <%= link_to "Back", books_path  %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container container px-5 px-sm-0">
  <!--Error-->
  <%= render 'layouts/errors', error: @book %>
  <div class="row">
    <div class="col-md-3">
      <!--User info-->
      <%= render 'users/userInfo', user: @user %>
      <div class="row">
    	  <%= link_to '',edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path(@user) " %>
  　   </div>
      <!--Create a book-->
      <%= render 'books/newBook', book: @book %>
    </div>
    <!--ここまで共通部分-->
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover table-inverse">
        <h2>Books</h2>
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg", size:"40x40"%>
                <% end %>
              </td>
              <div class="favo">
                <td><%= link_to book.title, book_path(book.id) %></td>
              </div>
              <td><%= book.body %></td>
              <%= render "favorites/favorite", book: book %>
              <td>コメント件数：<%= book.post_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--User info-->
      <%= render 'users/userInfo', user: @user %>
      <div class="row">
    	  <%= link_to '',edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path(@user) " %>
  　   </div>
      <!--Create a book-->
      <%= render 'books/newBook', book: @books %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg", size:"40x40" %><br><%= @user.name %>
              <% end %>
            </td>
            <td><%=link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <%= render "favorites/favorite", book: @book %>
            <td>コメント件数：<%= @book.post_comments.count %></td>
            <% if @user.id == current_user.id %>
              <td><%= link_to "Edit" , edit_book_path, class: "btn btn-sm btn-success edit_book" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger destroy_book","data-confirm" => "本当に消しますか？" %></td>
            <%end%>
          </tr>
        </tbody>
      </table>

      <div id="comments-<%= @book.id %>">
        <%= render 'post_comments/index', book: @book %>
      </div>
      <div class="new-comment">
         <%= render 'post_comments/form' %>
      </div>
    </div>
  </div>

app/views/favorites/_favorite.html.erb
<td id="favo-<%= book.id %>">
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete ,remote: true  do %>
      ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post,remote: true do %>
      ♡<%= book.favorites.count %>
    <% end %>
  <% end %>
</td>

app/views/favorites/create.js.erb
$("#favo-<%= @book.id %>").html("<%= j(render partial: "favorites/favorite", locals: {book: @book} ) %>");

app/views/favorites/destroy.js.erb
$("#favo-<%= @book.id %>").html("<%= j(render partial: "favorites/favorite", locals: {book: @book} ) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
          <h1 class="px-3 mx-auto">welcome to<span class="fas fa-book"></span><strong>Bookers</strong> !!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<span class="fas fa-book"></span><strong>Bookers</strong> !!</h1>
      <p>In <span class="fas fa-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>
<!--button-->
			<div class="btn-wrapper col-10 mx-auto">
				<div class="row">
					<%=link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
				</div>
				<div class="row">
					<%=link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
				</div>
			</div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<div class="error_explanation">
  <% if error.errors.any? %>
  <h3><%= error.errors.count %>errors prohibited this book from being saved:</h3>
  <% error.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto" id="navbarNavDropdown">
              <% if user_signed_in? %>
                <li class="">
                  <%= link_to 'Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li class="">
                  <%= link_to 'Users', users_path , class: "fas fa-users nav-link text-light" %>
                </li>
                <li class="">
                  <%= link_to 'Books', books_path, class: "fas fa-book-open nav-link text-light"  %>
                </li>
                <li class="">
                  <%= link_to "logout", destroy_user_session_path, method: :delete , class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>

              <% else %>
                <li class="">
                  <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
                </li>
                <li class="">
                  <%= link_to "About", about_path , class: "fas fa-link nav-link text-light"%>
                </li>
                <li class="">
                  <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>
                <li class="">
                  <%= link_to "Login", new_user_session_path , class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>

            </ul>
        </div>
     </nav>
    </header>

    <main>
      <p class="flash"><%= notice %></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_comments/_form.html.erb
<%= form_with(model:[@book, @post_comment], remote: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/post_comments/_index.html.erb
<table>
  <tbody>
  <% book.post_comments.each do |post_comment| %>
  <tr>
    <td>
      <%= link_to user_path(post_comment.user) do %>
          <%= attachment_image_tag post_comment.user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg", size:"40x40" %><br><%= post_comment.user.name %>
      <% end %>
    </td>
    <td><%= post_comment.comment %></td>
    <% if post_comment.user == current_user %>
    <td class="comment-delete">
      <%= link_to "削除", book_post_comment_path(post_comment.book, post_comment), method: :delete %>
    </td>
   <% end %>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/post_comments/create.js.erb
$("#comments-<%= @book.id %>").html("<%= j(render partial: 'post_comments/index', locals: {book: @book} )%>")
$('#post_comment_comment').val("");

app/views/post_comments/destroy.js.erb
$("#comments-<%= @book.id %>").html("<%= j(render partial: 'post_comments/index', locals: {book: @book} )%>")
$('#post_comment_comment').val("");

app/views/post_comments/index.js.erb
$("#comments").html("<%= j(render "post_comments/index", post_comments: @post_comment.post.post_comments) %>");
$("textarea").val("")

app/views/users/_userInfo.html.erb
<h2>User info</h2>
<table class="table">
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
  	<th>name</th>
  	<th><%= user.name %></th>
  </tr>
  <tr>
  	<th>introduction</th>
  	<th><%= user.introduction %></th>
  </tr>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/errors', error: @user %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, class:"form-control name",id:"user_name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" , class:"form-control-file user_image ", id:"user_profile_image"%>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_field :introduction, autofocus: true,class:"form-control user_introduction" ,id:"user_introduction"  %>
        </div>
        <div class="form-group">
           <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container container px-5 px-sm-0">
  <!--Error-->
   <%= render 'layouts/errors', error: @book %>
   <div class="row">
      <div class="col-md-3">
        <!--User info-->
        <%= render 'users/userInfo', user: @user %>
        <div class="row">
      	  <%= link_to '',edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path(@user) " %>
    　   </div>
        <!--Create a book-->
        <%= render 'books/newBook', book: @book %>
      </div>

  <!----Users index-->
    <div class="col-md-8 offset-md-1">
       <h2>Users</h2>
       <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg" , size:"40x40"%></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show" ,user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container container px-5 px-sm-0">
  <!--Error-->
  <%= render 'layouts/errors', error: @book %>
  <div class="row">
    <div class="col-md-3">
      <!--User info-->
      <%= render 'users/userInfo', user: @user %>
      <div class="row">
    	  <%= link_to '',edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path(@user) " %>
  　   </div>
      <!--Create a book-->
      <%= render 'books/newBook', book: @book %>
    </div>
    <!--ここまで共通部分-->
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover table-inverse">
        <h2>Book detail</h2>
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg", size:"40x40"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>